"""Add deleted_file table

Revision ID: 4378a15b09bb
Revises: 6910b68df770
Create Date: 2026-02-08 21:21:39.453619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4378a15b09bb'
down_revision = '6910b68df770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_file_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('grievance_summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_file')
    # ### end Alembic commands ###
